# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Li Zhineng's blog
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Li Zhineng.
  I am a web developer based in the city of Guangzhou, China.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhineng.li" # the base hostname & protocol for your site
github_username: lizhineng
google_plus_username: LiZhineng

# Build settings
markdown: kramdown
